### ISSUE TITLE
Fix regex or api path so that users/all will not be recognized as users/:uid

### ISSUE THREAD

**Issue by cadyzq** [cadyzq/PotatoServer#19]
![image](https://user-images.githubusercontent.com/21980161/151472044-519e5be9-abdd-4882-82e7-d96cf3efc7a7.png)

![image](https://user-images.githubusercontent.com/21980161/151473117-2e3fe05a-6a80-4485-957b-8604f3be9000.png)

**Comment by JacksonMcNabb** [comment]
Wrapper in view removes this bug
